package msg;

public enum KindM {
    CONNECTION, 
    CONNECTIONACK,
    USERLIST,
    USERLISTACK,
    SENDFILE,
    FILEREQUEST,
    FILEREQUESTACK,
    CLIENTSERVERREADY,
    SERVERCLIENTREADY,
    CLOSE,
    CLOSEACK,
    FILERECEIVED,
}
